
//! Autogenerated weights for pallet_avn_transaction_payment
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2025-04-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-172-31-2-182`, CPU: `AMD EPYC 7R32`
//! EXECUTION: ``, WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./avn-parachain-collator
// benchmark
// pallet
// --chain
// dev
// --wasm-execution=compiled
// --template
// frame-weight-template.hbs
// --pallet
// pallet_avn_transaction_payment
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// avn_transaction_payment_weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_avn_transaction_payment.
pub trait WeightInfo {
	fn set_known_sender() -> Weight;
	fn remove_known_sender() -> Weight;
	fn set_base_gas_fee_usd() -> Weight;
}

/// Weights for pallet_avn_transaction_payment using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `AvnTransactionPayment::KnownSenders` (r:1 w:1)
	/// Proof: `AvnTransactionPayment::KnownSenders` (`max_values`: None, `max_size`: Some(102), added: 2577, mode: `MaxEncodedLen`)
	fn set_known_sender() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `3567`
		// Minimum execution time: 13_640_000 picoseconds.
		Weight::from_parts(13_960_000, 3567)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AvnTransactionPayment::KnownSenders` (r:1 w:1)
	/// Proof: `AvnTransactionPayment::KnownSenders` (`max_values`: None, `max_size`: Some(102), added: 2577, mode: `MaxEncodedLen`)
	fn remove_known_sender() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `200`
		//  Estimated: `3567`
		// Minimum execution time: 15_351_000 picoseconds.
		Weight::from_parts(15_710_000, 3567)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
		/// Storage: `AvnTransactionPayment::BaseGasFeeUsd` (r:1 w:1)
	/// Proof: `AvnTransactionPayment::BaseGasFeeUsd` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn set_base_gas_fee_usd() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `149`
		//  Estimated: `1501`
		// Minimum execution time: 4_772_000 picoseconds.
		Weight::from_parts(5_088_000, 1501)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `AvnTransactionPayment::KnownSenders` (r:1 w:1)
	/// Proof: `AvnTransactionPayment::KnownSenders` (`max_values`: None, `max_size`: Some(102), added: 2577, mode: `MaxEncodedLen`)
	fn set_known_sender() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `3567`
		// Minimum execution time: 13_640_000 picoseconds.
		Weight::from_parts(13_960_000, 3567)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AvnTransactionPayment::KnownSenders` (r:1 w:1)
	/// Proof: `AvnTransactionPayment::KnownSenders` (`max_values`: None, `max_size`: Some(102), added: 2577, mode: `MaxEncodedLen`)
	fn remove_known_sender() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `200`
		//  Estimated: `3567`
		// Minimum execution time: 15_351_000 picoseconds.
		Weight::from_parts(15_710_000, 3567)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
		/// Storage: `AvnTransactionPayment::BaseGasFeeUsd` (r:1 w:1)
	/// Proof: `AvnTransactionPayment::BaseGasFeeUsd` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn set_base_gas_fee_usd() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `149`
		//  Estimated: `1501`
		// Minimum execution time: 4_772_000 picoseconds.
		Weight::from_parts(5_088_000, 1501)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}