
//! Autogenerated weights for pallet_token_manager
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2026-01-14, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `aventus-GM5IX0A`, CPU: `Intel(R) Core(TM) i9-14900HX`
//! EXECUTION: ``, WASM-EXECUTION: `Compiled`, CHAIN: `Some("local")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/avn-parachain-collator
// benchmark
// pallet
// --chain
// local
// --wasm-execution=compiled
// --template
// .maintain/frame-weight-template.hbs
// --pallet
// pallet_token_manager
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/token-manager/src/default_weights_2.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_token_manager.
pub trait WeightInfo {
	fn proxy_with_non_avt_token() -> Weight;
	fn signed_transfer() -> Weight;
	fn schedule_direct_lower() -> Weight;
	fn execute_avt_lower() -> Weight;
	fn execute_non_avt_lower() -> Weight;
	fn schedule_signed_lower() -> Weight;
	fn transfer_from_treasury() -> Weight;
	fn regenerate_lower_proof() -> Weight;
	fn set_lower_schedule_period() -> Weight;
	fn toggle_lowering() -> Weight;
	fn set_burn_period() -> Weight;
	fn on_initialize_burn_due_and_pot_has_funds_to_burn() -> Weight;
	fn on_initialize_burn_not_due() -> Weight;
	fn on_initialize_burn_due_but_pot_empty() -> Weight;
	fn burn_funds() -> Weight;
}

/// Weights for pallet_token_manager using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `TokenManager::Nonces` (r:1 w:1)
	/// Proof: `TokenManager::Nonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::Balances` (r:2 w:2)
	/// Proof: `TokenManager::Balances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn proxy_with_non_avt_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `657`
		//  Estimated: `6108`
		// Minimum execution time: 81_476_000 picoseconds.
		Weight::from_parts(83_449_000, 6108)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `TokenManager::Nonces` (r:1 w:1)
	/// Proof: `TokenManager::Nonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::Balances` (r:2 w:2)
	/// Proof: `TokenManager::Balances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn signed_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `657`
		//  Estimated: `6108`
		// Minimum execution time: 77_746_000 picoseconds.
		Weight::from_parts(79_453_000, 6108)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `TokenManager::LowersDisabled` (r:1 w:0)
	/// Proof: `TokenManager::LowersDisabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowerAccountId` (r:1 w:0)
	/// Proof: `TokenManager::LowerAccountId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowerNonce` (r:1 w:1)
	/// Proof: `TokenManager::LowerNonce` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowerSchedulePeriod` (r:1 w:0)
	/// Proof: `TokenManager::LowerSchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(38963), added: 41438, mode: `MaxEncodedLen`)
	fn schedule_direct_lower() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `154`
		//  Estimated: `42428`
		// Minimum execution time: 17_631_000 picoseconds.
		Weight::from_parts(18_349_000, 42428)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `TokenManager::LowersDisabled` (r:1 w:0)
	/// Proof: `TokenManager::LowersDisabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:1)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20944), added: 21439, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowersPendingProof` (r:0 w:1)
	/// Proof: `TokenManager::LowersPendingProof` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	fn execute_avt_lower() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `361`
		//  Estimated: `22429`
		// Minimum execution time: 25_892_000 picoseconds.
		Weight::from_parts(26_700_000, 22429)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `TokenManager::LowersDisabled` (r:1 w:0)
	/// Proof: `TokenManager::LowersDisabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::Balances` (r:1 w:1)
	/// Proof: `TokenManager::Balances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:1)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20944), added: 21439, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowersPendingProof` (r:0 w:1)
	/// Proof: `TokenManager::LowersPendingProof` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	fn execute_non_avt_lower() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `601`
		//  Estimated: `22429`
		// Minimum execution time: 19_901_000 picoseconds.
		Weight::from_parts(20_718_000, 22429)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `TokenManager::LowersDisabled` (r:1 w:0)
	/// Proof: `TokenManager::LowersDisabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::Nonces` (r:1 w:1)
	/// Proof: `TokenManager::Nonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowerAccountId` (r:1 w:0)
	/// Proof: `TokenManager::LowerAccountId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowerNonce` (r:1 w:1)
	/// Proof: `TokenManager::LowerNonce` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowerSchedulePeriod` (r:1 w:0)
	/// Proof: `TokenManager::LowerSchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(38963), added: 41438, mode: `MaxEncodedLen`)
	fn schedule_signed_lower() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `440`
		//  Estimated: `42428`
		// Minimum execution time: 78_719_000 picoseconds.
		Weight::from_parts(80_727_000, 42428)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn transfer_from_treasury() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `226`
		//  Estimated: `6196`
		// Minimum execution time: 32_711_000 picoseconds.
		Weight::from_parts(33_627_000, 6196)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `TokenManager::LowersReadyToClaim` (r:1 w:1)
	/// Proof: `TokenManager::LowersReadyToClaim` (`max_values`: None, `max_size`: Some(10098), added: 12573, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:1)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20944), added: 21439, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowersPendingProof` (r:0 w:1)
	/// Proof: `TokenManager::LowersPendingProof` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	fn regenerate_lower_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `371`
		//  Estimated: `22429`
		// Minimum execution time: 16_553_000 picoseconds.
		Weight::from_parts(17_402_000, 22429)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `TokenManager::LowerSchedulePeriod` (r:0 w:1)
	/// Proof: `TokenManager::LowerSchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_lower_schedule_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_244_000 picoseconds.
		Weight::from_parts(3_392_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TokenManager::LowersDisabled` (r:0 w:1)
	/// Proof: `TokenManager::LowersDisabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn toggle_lowering() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_120_000 picoseconds.
		Weight::from_parts(3_302_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TokenManager::BurnPeriod` (r:0 w:1)
	/// Proof: `TokenManager::BurnPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_burn_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_192_000 picoseconds.
		Weight::from_parts(3_345_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TokenManager::NextBurnAt` (r:1 w:1)
	/// Proof: `TokenManager::NextBurnAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::BurnPeriod` (r:1 w:0)
	/// Proof: `TokenManager::BurnPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::NextTxId` (r:1 w:1)
	/// Proof: `EthBridge::NextTxId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:1)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20944), added: 21439, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::EthTxLifetimeSecs` (r:1 w:0)
	/// Proof: `EthBridge::EthTxLifetimeSecs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Avn::PrimaryCollatorIndexForSending` (r:1 w:1)
	/// Proof: `Avn::PrimaryCollatorIndexForSending` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::PendingBurnSubmission` (r:0 w:1)
	/// Proof: `TokenManager::PendingBurnSubmission` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	fn on_initialize_burn_due_and_pot_has_funds_to_burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `743`
		//  Estimated: `22429`
		// Minimum execution time: 34_028_000 picoseconds.
		Weight::from_parts(34_950_000, 22429)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `TokenManager::NextBurnAt` (r:1 w:0)
	/// Proof: `TokenManager::NextBurnAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn on_initialize_burn_not_due() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `154`
		//  Estimated: `1489`
		// Minimum execution time: 2_206_000 picoseconds.
		Weight::from_parts(2_410_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `TokenManager::NextBurnAt` (r:1 w:1)
	/// Proof: `TokenManager::NextBurnAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::BurnPeriod` (r:1 w:0)
	/// Proof: `TokenManager::BurnPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn on_initialize_burn_due_but_pot_empty() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `206`
		//  Estimated: `3593`
		// Minimum execution time: 4_541_000 picoseconds.
		Weight::from_parts(4_923_000, 3593)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `EthBridge::NextTxId` (r:1 w:1)
	/// Proof: `EthBridge::NextTxId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:1)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20944), added: 21439, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::EthTxLifetimeSecs` (r:1 w:0)
	/// Proof: `EthBridge::EthTxLifetimeSecs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Avn::PrimaryCollatorIndexForSending` (r:1 w:1)
	/// Proof: `Avn::PrimaryCollatorIndexForSending` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::PendingBurnSubmission` (r:0 w:1)
	/// Proof: `TokenManager::PendingBurnSubmission` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	fn burn_funds() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `449`
		//  Estimated: `22429`
		// Minimum execution time: 32_531_000 picoseconds.
		Weight::from_parts(33_850_000, 22429)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `TokenManager::Nonces` (r:1 w:1)
	/// Proof: `TokenManager::Nonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::Balances` (r:2 w:2)
	/// Proof: `TokenManager::Balances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn proxy_with_non_avt_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `657`
		//  Estimated: `6108`
		// Minimum execution time: 81_476_000 picoseconds.
		Weight::from_parts(83_449_000, 6108)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `TokenManager::Nonces` (r:1 w:1)
	/// Proof: `TokenManager::Nonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::Balances` (r:2 w:2)
	/// Proof: `TokenManager::Balances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn signed_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `657`
		//  Estimated: `6108`
		// Minimum execution time: 77_746_000 picoseconds.
		Weight::from_parts(79_453_000, 6108)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `TokenManager::LowersDisabled` (r:1 w:0)
	/// Proof: `TokenManager::LowersDisabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowerAccountId` (r:1 w:0)
	/// Proof: `TokenManager::LowerAccountId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowerNonce` (r:1 w:1)
	/// Proof: `TokenManager::LowerNonce` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowerSchedulePeriod` (r:1 w:0)
	/// Proof: `TokenManager::LowerSchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(38963), added: 41438, mode: `MaxEncodedLen`)
	fn schedule_direct_lower() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `154`
		//  Estimated: `42428`
		// Minimum execution time: 17_631_000 picoseconds.
		Weight::from_parts(18_349_000, 42428)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `TokenManager::LowersDisabled` (r:1 w:0)
	/// Proof: `TokenManager::LowersDisabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:1)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20944), added: 21439, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowersPendingProof` (r:0 w:1)
	/// Proof: `TokenManager::LowersPendingProof` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	fn execute_avt_lower() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `361`
		//  Estimated: `22429`
		// Minimum execution time: 25_892_000 picoseconds.
		Weight::from_parts(26_700_000, 22429)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `TokenManager::LowersDisabled` (r:1 w:0)
	/// Proof: `TokenManager::LowersDisabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::Balances` (r:1 w:1)
	/// Proof: `TokenManager::Balances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:1)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20944), added: 21439, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowersPendingProof` (r:0 w:1)
	/// Proof: `TokenManager::LowersPendingProof` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	fn execute_non_avt_lower() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `601`
		//  Estimated: `22429`
		// Minimum execution time: 19_901_000 picoseconds.
		Weight::from_parts(20_718_000, 22429)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `TokenManager::LowersDisabled` (r:1 w:0)
	/// Proof: `TokenManager::LowersDisabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::Nonces` (r:1 w:1)
	/// Proof: `TokenManager::Nonces` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowerAccountId` (r:1 w:0)
	/// Proof: `TokenManager::LowerAccountId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowerNonce` (r:1 w:1)
	/// Proof: `TokenManager::LowerNonce` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowerSchedulePeriod` (r:1 w:0)
	/// Proof: `TokenManager::LowerSchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(38963), added: 41438, mode: `MaxEncodedLen`)
	fn schedule_signed_lower() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `440`
		//  Estimated: `42428`
		// Minimum execution time: 78_719_000 picoseconds.
		Weight::from_parts(80_727_000, 42428)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn transfer_from_treasury() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `226`
		//  Estimated: `6196`
		// Minimum execution time: 32_711_000 picoseconds.
		Weight::from_parts(33_627_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `TokenManager::LowersReadyToClaim` (r:1 w:1)
	/// Proof: `TokenManager::LowersReadyToClaim` (`max_values`: None, `max_size`: Some(10098), added: 12573, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:1)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20944), added: 21439, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::LowersPendingProof` (r:0 w:1)
	/// Proof: `TokenManager::LowersPendingProof` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	fn regenerate_lower_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `371`
		//  Estimated: `22429`
		// Minimum execution time: 16_553_000 picoseconds.
		Weight::from_parts(17_402_000, 22429)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `TokenManager::LowerSchedulePeriod` (r:0 w:1)
	/// Proof: `TokenManager::LowerSchedulePeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_lower_schedule_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_244_000 picoseconds.
		Weight::from_parts(3_392_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TokenManager::LowersDisabled` (r:0 w:1)
	/// Proof: `TokenManager::LowersDisabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn toggle_lowering() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_120_000 picoseconds.
		Weight::from_parts(3_302_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TokenManager::BurnPeriod` (r:0 w:1)
	/// Proof: `TokenManager::BurnPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_burn_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_192_000 picoseconds.
		Weight::from_parts(3_345_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TokenManager::NextBurnAt` (r:1 w:1)
	/// Proof: `TokenManager::NextBurnAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::BurnPeriod` (r:1 w:0)
	/// Proof: `TokenManager::BurnPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::NextTxId` (r:1 w:1)
	/// Proof: `EthBridge::NextTxId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:1)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20944), added: 21439, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::EthTxLifetimeSecs` (r:1 w:0)
	/// Proof: `EthBridge::EthTxLifetimeSecs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Avn::PrimaryCollatorIndexForSending` (r:1 w:1)
	/// Proof: `Avn::PrimaryCollatorIndexForSending` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::PendingBurnSubmission` (r:0 w:1)
	/// Proof: `TokenManager::PendingBurnSubmission` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	fn on_initialize_burn_due_and_pot_has_funds_to_burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `743`
		//  Estimated: `22429`
		// Minimum execution time: 34_028_000 picoseconds.
		Weight::from_parts(34_950_000, 22429)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `TokenManager::NextBurnAt` (r:1 w:0)
	/// Proof: `TokenManager::NextBurnAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn on_initialize_burn_not_due() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `154`
		//  Estimated: `1489`
		// Minimum execution time: 2_206_000 picoseconds.
		Weight::from_parts(2_410_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	/// Storage: `TokenManager::NextBurnAt` (r:1 w:1)
	/// Proof: `TokenManager::NextBurnAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::BurnPeriod` (r:1 w:0)
	/// Proof: `TokenManager::BurnPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn on_initialize_burn_due_but_pot_empty() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `206`
		//  Estimated: `3593`
		// Minimum execution time: 4_541_000 picoseconds.
		Weight::from_parts(4_923_000, 3593)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `EthBridge::NextTxId` (r:1 w:1)
	/// Proof: `EthBridge::NextTxId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::ActiveRequest` (r:1 w:1)
	/// Proof: `EthBridge::ActiveRequest` (`max_values`: Some(1), `max_size`: Some(20944), added: 21439, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::EthTxLifetimeSecs` (r:1 w:0)
	/// Proof: `EthBridge::EthTxLifetimeSecs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Avn::Validators` (r:1 w:0)
	/// Proof: `Avn::Validators` (`max_values`: Some(1), `max_size`: Some(16386), added: 16881, mode: `MaxEncodedLen`)
	/// Storage: `Avn::PrimaryCollatorIndexForSending` (r:1 w:1)
	/// Proof: `Avn::PrimaryCollatorIndexForSending` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::PendingBurnSubmission` (r:0 w:1)
	/// Proof: `TokenManager::PendingBurnSubmission` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	fn burn_funds() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `449`
		//  Estimated: `22429`
		// Minimum execution time: 32_531_000 picoseconds.
		Weight::from_parts(33_850_000, 22429)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
}