//! Autogenerated weights for pallet_avn_anchor
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 48.0.0
//! DATE: 2026-06-24, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-172-31-1-153`, CPU: `AMD EPYC 7R32`
//! EXECUTION: ``, WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./avn-parachain-collator
// benchmark
// pallet
// --chain
// dev
// --wasm-execution=compiled
// --template
// frame-weight-template.hbs
// --pallet
// pallet_avn_anchor
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// avn_anchor_weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_avn_anchor.
pub trait WeightInfo {
	fn register_chain_handler() -> Weight;
	fn update_chain_handler() -> Weight;
	fn submit_checkpoint_with_identity() -> Weight;
	fn signed_register_chain_handler() -> Weight;
	fn signed_update_chain_handler() -> Weight;
	fn signed_submit_checkpoint_with_identity() -> Weight;
	fn register_appchain() -> Weight;
	fn set_checkpoint_fee() -> Weight;
	fn set_appchain_period_reward() -> Weight;
	fn on_new_reward_period(n: u32, ) -> Weight;
	fn pay_node_period(n: u32, ) -> Weight;
	fn claim(p: u32, c: u32, ) -> Weight;
	fn process_outstanding_rewards(n: u32, c: u32, ) -> Weight;
	fn on_reward_paid(b: u32, ) -> Weight;
}

/// Weights for pallet_avn_anchor using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn register_chain_handler() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_385_000 picoseconds.
		Weight::from_parts(3_886_000, 0)
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:2 w:2)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn update_chain_handler() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `139`
		//  Estimated: `6044`
		// Minimum execution time: 24_908_000 picoseconds.
		Weight::from_parts(27_177_000, 6044)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:1 w:0)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::OriginIdToCheckpoint` (r:1 w:1)
	/// Proof: `AvnAnchor::OriginIdToCheckpoint` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::NextCheckpointId` (r:1 w:1)
	/// Proof: `AvnAnchor::NextCheckpointId` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Nonces` (r:1 w:1)
	/// Proof: `AvnAnchor::Nonces` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::CheckpointFee` (r:1 w:0)
	/// Proof: `AvnAnchor::CheckpointFee` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Checkpoints` (r:0 w:1)
	/// Proof: `AvnAnchor::Checkpoints` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn submit_checkpoint_with_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `699`
		//  Estimated: `6196`
		// Minimum execution time: 98_371_000 picoseconds.
		Weight::from_parts(107_133_000, 6196)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	fn signed_register_chain_handler() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_520_000 picoseconds.
		Weight::from_parts(4_070_000, 0)
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:2 w:2)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Nonces` (r:1 w:1)
	/// Proof: `AvnAnchor::Nonces` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn signed_update_chain_handler() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `155`
		//  Estimated: `6044`
		// Minimum execution time: 114_095_000 picoseconds.
		Weight::from_parts(133_164_000, 6044)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:1 w:0)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Nonces` (r:1 w:1)
	/// Proof: `AvnAnchor::Nonces` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::OriginIdToCheckpoint` (r:1 w:1)
	/// Proof: `AvnAnchor::OriginIdToCheckpoint` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::NextCheckpointId` (r:1 w:1)
	/// Proof: `AvnAnchor::NextCheckpointId` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::CheckpointFee` (r:1 w:0)
	/// Proof: `AvnAnchor::CheckpointFee` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Checkpoints` (r:0 w:1)
	/// Proof: `AvnAnchor::Checkpoints` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn signed_submit_checkpoint_with_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `665`
		//  Estimated: `6196`
		// Minimum execution time: 195_914_000 picoseconds.
		Weight::from_parts(230_968_000, 6196)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:1 w:1)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:1)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::NextChainId` (r:1 w:1)
	/// Proof: `AvnAnchor::NextChainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::Metadata` (r:1 w:1)
	/// Proof: `AssetRegistry::Metadata` (`max_values`: None, `max_size`: Some(2698), added: 5173, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::RegisteredAppchains` (r:1 w:1)
	/// Proof: `AvnAnchor::RegisteredAppchains` (`max_values`: Some(1), `max_size`: Some(126), added: 621, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::AssetIdToChainId` (r:0 w:1)
	/// Proof: `AvnAnchor::AssetIdToChainId` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn register_appchain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `233`
		//  Estimated: `6163`
		// Minimum execution time: 39_011_000 picoseconds.
		Weight::from_parts(44_746_000, 6163)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `AvnAnchor::CheckpointFee` (r:0 w:1)
	/// Proof: `AvnAnchor::CheckpointFee` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn set_checkpoint_fee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_749_000 picoseconds.
		Weight::from_parts(10_869_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AvnAnchor::AssetIdToChainId` (r:1 w:0)
	/// Proof: `AvnAnchor::AssetIdToChainId` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::ChainHandlers` (r:1 w:0)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::Metadata` (r:1 w:0)
	/// Proof: `AssetRegistry::Metadata` (`max_values`: None, `max_size`: Some(2698), added: 5173, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::NextRewardAmountPerPeriod` (r:0 w:1)
	/// Proof: `AvnAnchor::NextRewardAmountPerPeriod` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	fn set_appchain_period_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `445`
		//  Estimated: `6163`
		// Minimum execution time: 32_631_000 picoseconds.
		Weight::from_parts(33_729_000, 6163)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AvnAnchor::NextRewardAmountPerPeriod` (r:26 w:0)
	/// Proof: `AvnAnchor::NextRewardAmountPerPeriod` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::PeriodChainReward` (r:0 w:25)
	/// Proof: `AvnAnchor::PeriodChainReward` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 25]`.
	fn on_new_reward_period(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `215 + n * (85 ±0)`
		//  Estimated: `3522 + n * (2532 ±0)`
		// Minimum execution time: 13_901_000 picoseconds.
		Weight::from_parts(12_893_911, 3522)
			// Standard Error: 51_319
			.saturating_add(Weight::from_parts(7_504_517, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2532).saturating_mul(n.into()))
	}
	/// Storage: `AvnAnchor::UnpaidByPeriod` (r:2 w:1)
	/// Proof: `AvnAnchor::UnpaidByPeriod` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::PeriodChainReward` (r:26 w:25)
	/// Proof: `AvnAnchor::PeriodChainReward` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:25 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `OrmlTokens::Accounts` (r:50 w:50)
	/// Proof: `OrmlTokens::Accounts` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::Metadata` (r:25 w:0)
	/// Proof: `AssetRegistry::Metadata` (`max_values`: None, `max_size`: Some(2698), added: 5173, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::UnpaidByNode` (r:1 w:1)
	/// Proof: `AvnAnchor::UnpaidByNode` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 25]`.
	fn pay_node_period(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `810 + n * (261 ±0)`
		//  Estimated: `6164 + n * (5173 ±0)`
		// Minimum execution time: 91_517_000 picoseconds.
		Weight::from_parts(34_691_619, 6164)
			// Standard Error: 654_074
			.saturating_add(Weight::from_parts(51_613_956, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().reads((5_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 5173).saturating_mul(n.into()))
	}
	/// Storage: `AvnAnchor::UnpaidByNode` (r:11 w:10)
	/// Proof: `AvnAnchor::UnpaidByNode` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::UnpaidByPeriod` (r:20 w:10)
	/// Proof: `AvnAnchor::UnpaidByPeriod` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::PeriodChainReward` (r:260 w:250)
	/// Proof: `AvnAnchor::PeriodChainReward` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:25 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `OrmlTokens::Accounts` (r:50 w:50)
	/// Proof: `OrmlTokens::Accounts` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::Metadata` (r:25 w:0)
	/// Proof: `AssetRegistry::Metadata` (`max_values`: None, `max_size`: Some(2698), added: 5173, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 10]`.
	/// The range of component `c` is `[1, 25]`.
	fn claim(p: u32, c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + c * (834 ±0) + p * (1774 ±0)`
		//  Estimated: `52110 + c * (8150 ±0) + p * (21057 ±0)`
		// Minimum execution time: 676_854_000 picoseconds.
		Weight::from_parts(769_513_000, 52110)
			// Standard Error: 8_937_127
			.saturating_add(Weight::from_parts(249_578_132, 0).saturating_mul(p.into()))
			// Standard Error: 3_558_957
			.saturating_add(Weight::from_parts(120_994_094, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(56_u64))
			.saturating_add(T::DbWeight::get().reads((9_u64).saturating_mul(p.into())))
			.saturating_add(T::DbWeight::get().reads((6_u64).saturating_mul(c.into())))
			.saturating_add(T::DbWeight::get().writes(33_u64))
			.saturating_add(T::DbWeight::get().writes((8_u64).saturating_mul(p.into())))
			.saturating_add(T::DbWeight::get().writes((5_u64).saturating_mul(c.into())))
			.saturating_add(Weight::from_parts(0, 8150).saturating_mul(c.into()))
			.saturating_add(Weight::from_parts(0, 21057).saturating_mul(p.into()))
	}
	/// Storage: `AvnAnchor::SweepCursor` (r:1 w:1)
	/// Proof: `AvnAnchor::SweepCursor` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::UnpaidByPeriod` (r:12 w:10)
	/// Proof: `AvnAnchor::UnpaidByPeriod` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::PeriodChainReward` (r:26 w:25)
	/// Proof: `AvnAnchor::PeriodChainReward` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:25 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `OrmlTokens::Accounts` (r:50 w:50)
	/// Proof: `OrmlTokens::Accounts` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::Metadata` (r:25 w:0)
	/// Proof: `AssetRegistry::Metadata` (`max_values`: None, `max_size`: Some(2698), added: 5173, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::UnpaidByNode` (r:10 w:10)
	/// Proof: `AvnAnchor::UnpaidByNode` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	/// The range of component `c` is `[1, 25]`.
	fn process_outstanding_rewards(n: u32, c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `646 + c * (261 ±0) + n * (174 ±0)`
		//  Estimated: `6164 + c * (5173 ±0) + n * (2587 ±0)`
		// Minimum execution time: 578_642_000 picoseconds.
		Weight::from_parts(641_916_000, 6164)
			// Standard Error: 8_093_414
			.saturating_add(Weight::from_parts(227_805_604, 0).saturating_mul(n.into()))
			// Standard Error: 3_222_972
			.saturating_add(Weight::from_parts(105_688_970, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().reads((5_u64).saturating_mul(c.into())))
			.saturating_add(T::DbWeight::get().writes(2_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(c.into())))
			.saturating_add(Weight::from_parts(0, 5173).saturating_mul(c.into()))
			.saturating_add(Weight::from_parts(0, 2587).saturating_mul(n.into()))
	}
	/// Storage: `AvnAnchor::PeriodChainReward` (r:2 w:0)
	/// Proof: `AvnAnchor::PeriodChainReward` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::UnpaidByPeriod` (r:0 w:999)
	/// Proof: `AvnAnchor::UnpaidByPeriod` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::UnpaidByNode` (r:0 w:999)
	/// Proof: `AvnAnchor::UnpaidByNode` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[1, 1000]`.
	fn on_reward_paid(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `261`
		//  Estimated: `6102`
		// Minimum execution time: 14_457_000 picoseconds.
		Weight::from_parts(15_537_000, 6102)
			// Standard Error: 23_394
			.saturating_add(Weight::from_parts(10_699_515, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(b.into())))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	fn register_chain_handler() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_385_000 picoseconds.
		Weight::from_parts(3_886_000, 0)
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:2 w:2)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn update_chain_handler() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `139`
		//  Estimated: `6044`
		// Minimum execution time: 24_908_000 picoseconds.
		Weight::from_parts(27_177_000, 6044)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:1 w:0)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::OriginIdToCheckpoint` (r:1 w:1)
	/// Proof: `AvnAnchor::OriginIdToCheckpoint` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::NextCheckpointId` (r:1 w:1)
	/// Proof: `AvnAnchor::NextCheckpointId` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Nonces` (r:1 w:1)
	/// Proof: `AvnAnchor::Nonces` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::CheckpointFee` (r:1 w:0)
	/// Proof: `AvnAnchor::CheckpointFee` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Checkpoints` (r:0 w:1)
	/// Proof: `AvnAnchor::Checkpoints` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn submit_checkpoint_with_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `699`
		//  Estimated: `6196`
		// Minimum execution time: 98_371_000 picoseconds.
		Weight::from_parts(107_133_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	fn signed_register_chain_handler() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_520_000 picoseconds.
		Weight::from_parts(4_070_000, 0)
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:2 w:2)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Nonces` (r:1 w:1)
	/// Proof: `AvnAnchor::Nonces` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn signed_update_chain_handler() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `155`
		//  Estimated: `6044`
		// Minimum execution time: 114_095_000 picoseconds.
		Weight::from_parts(133_164_000, 6044)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:1 w:0)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Nonces` (r:1 w:1)
	/// Proof: `AvnAnchor::Nonces` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::OriginIdToCheckpoint` (r:1 w:1)
	/// Proof: `AvnAnchor::OriginIdToCheckpoint` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::NextCheckpointId` (r:1 w:1)
	/// Proof: `AvnAnchor::NextCheckpointId` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::CheckpointFee` (r:1 w:0)
	/// Proof: `AvnAnchor::CheckpointFee` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Checkpoints` (r:0 w:1)
	/// Proof: `AvnAnchor::Checkpoints` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn signed_submit_checkpoint_with_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `665`
		//  Estimated: `6196`
		// Minimum execution time: 195_914_000 picoseconds.
		Weight::from_parts(230_968_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:1 w:1)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:1)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::NextChainId` (r:1 w:1)
	/// Proof: `AvnAnchor::NextChainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::Metadata` (r:1 w:1)
	/// Proof: `AssetRegistry::Metadata` (`max_values`: None, `max_size`: Some(2698), added: 5173, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::RegisteredAppchains` (r:1 w:1)
	/// Proof: `AvnAnchor::RegisteredAppchains` (`max_values`: Some(1), `max_size`: Some(126), added: 621, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::AssetIdToChainId` (r:0 w:1)
	/// Proof: `AvnAnchor::AssetIdToChainId` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn register_appchain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `233`
		//  Estimated: `6163`
		// Minimum execution time: 39_011_000 picoseconds.
		Weight::from_parts(44_746_000, 6163)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `AvnAnchor::CheckpointFee` (r:0 w:1)
	/// Proof: `AvnAnchor::CheckpointFee` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn set_checkpoint_fee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_749_000 picoseconds.
		Weight::from_parts(10_869_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AvnAnchor::AssetIdToChainId` (r:1 w:0)
	/// Proof: `AvnAnchor::AssetIdToChainId` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::ChainHandlers` (r:1 w:0)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::Metadata` (r:1 w:0)
	/// Proof: `AssetRegistry::Metadata` (`max_values`: None, `max_size`: Some(2698), added: 5173, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::NextRewardAmountPerPeriod` (r:0 w:1)
	/// Proof: `AvnAnchor::NextRewardAmountPerPeriod` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	fn set_appchain_period_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `445`
		//  Estimated: `6163`
		// Minimum execution time: 32_631_000 picoseconds.
		Weight::from_parts(33_729_000, 6163)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AvnAnchor::NextRewardAmountPerPeriod` (r:26 w:0)
	/// Proof: `AvnAnchor::NextRewardAmountPerPeriod` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::PeriodChainReward` (r:0 w:25)
	/// Proof: `AvnAnchor::PeriodChainReward` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 25]`.
	fn on_new_reward_period(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `215 + n * (85 ±0)`
		//  Estimated: `3522 + n * (2532 ±0)`
		// Minimum execution time: 13_901_000 picoseconds.
		Weight::from_parts(12_893_911, 3522)
			// Standard Error: 51_319
			.saturating_add(Weight::from_parts(7_504_517, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2532).saturating_mul(n.into()))
	}
	/// Storage: `AvnAnchor::UnpaidByPeriod` (r:2 w:1)
	/// Proof: `AvnAnchor::UnpaidByPeriod` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::PeriodChainReward` (r:26 w:25)
	/// Proof: `AvnAnchor::PeriodChainReward` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:25 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `OrmlTokens::Accounts` (r:50 w:50)
	/// Proof: `OrmlTokens::Accounts` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::Metadata` (r:25 w:0)
	/// Proof: `AssetRegistry::Metadata` (`max_values`: None, `max_size`: Some(2698), added: 5173, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::UnpaidByNode` (r:1 w:1)
	/// Proof: `AvnAnchor::UnpaidByNode` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 25]`.
	fn pay_node_period(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `810 + n * (261 ±0)`
		//  Estimated: `6164 + n * (5173 ±0)`
		// Minimum execution time: 91_517_000 picoseconds.
		Weight::from_parts(34_691_619, 6164)
			// Standard Error: 654_074
			.saturating_add(Weight::from_parts(51_613_956, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().reads((5_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
			.saturating_add(RocksDbWeight::get().writes((3_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 5173).saturating_mul(n.into()))
	}
	/// Storage: `AvnAnchor::UnpaidByNode` (r:11 w:10)
	/// Proof: `AvnAnchor::UnpaidByNode` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::UnpaidByPeriod` (r:20 w:10)
	/// Proof: `AvnAnchor::UnpaidByPeriod` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::PeriodChainReward` (r:260 w:250)
	/// Proof: `AvnAnchor::PeriodChainReward` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:25 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `OrmlTokens::Accounts` (r:50 w:50)
	/// Proof: `OrmlTokens::Accounts` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::Metadata` (r:25 w:0)
	/// Proof: `AssetRegistry::Metadata` (`max_values`: None, `max_size`: Some(2698), added: 5173, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 10]`.
	/// The range of component `c` is `[1, 25]`.
	fn claim(p: u32, c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + c * (834 ±0) + p * (1774 ±0)`
		//  Estimated: `52110 + c * (8150 ±0) + p * (21057 ±0)`
		// Minimum execution time: 676_854_000 picoseconds.
		Weight::from_parts(769_513_000, 52110)
			// Standard Error: 8_937_127
			.saturating_add(Weight::from_parts(249_578_132, 0).saturating_mul(p.into()))
			// Standard Error: 3_558_957
			.saturating_add(Weight::from_parts(120_994_094, 0).saturating_mul(c.into()))
			.saturating_add(RocksDbWeight::get().reads(56_u64))
			.saturating_add(RocksDbWeight::get().reads((9_u64).saturating_mul(p.into())))
			.saturating_add(RocksDbWeight::get().reads((6_u64).saturating_mul(c.into())))
			.saturating_add(RocksDbWeight::get().writes(33_u64))
			.saturating_add(RocksDbWeight::get().writes((8_u64).saturating_mul(p.into())))
			.saturating_add(RocksDbWeight::get().writes((5_u64).saturating_mul(c.into())))
			.saturating_add(Weight::from_parts(0, 8150).saturating_mul(c.into()))
			.saturating_add(Weight::from_parts(0, 21057).saturating_mul(p.into()))
	}
	/// Storage: `AvnAnchor::SweepCursor` (r:1 w:1)
	/// Proof: `AvnAnchor::SweepCursor` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::UnpaidByPeriod` (r:12 w:10)
	/// Proof: `AvnAnchor::UnpaidByPeriod` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::PeriodChainReward` (r:26 w:25)
	/// Proof: `AvnAnchor::PeriodChainReward` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:25 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `OrmlTokens::Accounts` (r:50 w:50)
	/// Proof: `OrmlTokens::Accounts` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::Metadata` (r:25 w:0)
	/// Proof: `AssetRegistry::Metadata` (`max_values`: None, `max_size`: Some(2698), added: 5173, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::UnpaidByNode` (r:10 w:10)
	/// Proof: `AvnAnchor::UnpaidByNode` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	/// The range of component `c` is `[1, 25]`.
	fn process_outstanding_rewards(n: u32, c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `646 + c * (261 ±0) + n * (174 ±0)`
		//  Estimated: `6164 + c * (5173 ±0) + n * (2587 ±0)`
		// Minimum execution time: 578_642_000 picoseconds.
		Weight::from_parts(641_916_000, 6164)
			// Standard Error: 8_093_414
			.saturating_add(Weight::from_parts(227_805_604, 0).saturating_mul(n.into()))
			// Standard Error: 3_222_972
			.saturating_add(Weight::from_parts(105_688_970, 0).saturating_mul(c.into()))
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().reads((5_u64).saturating_mul(c.into())))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes((3_u64).saturating_mul(c.into())))
			.saturating_add(Weight::from_parts(0, 5173).saturating_mul(c.into()))
			.saturating_add(Weight::from_parts(0, 2587).saturating_mul(n.into()))
	}
	/// Storage: `AvnAnchor::PeriodChainReward` (r:2 w:0)
	/// Proof: `AvnAnchor::PeriodChainReward` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::UnpaidByPeriod` (r:0 w:999)
	/// Proof: `AvnAnchor::UnpaidByPeriod` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::UnpaidByNode` (r:0 w:999)
	/// Proof: `AvnAnchor::UnpaidByNode` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[1, 1000]`.
	fn on_reward_paid(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `261`
		//  Estimated: `6102`
		// Minimum execution time: 14_457_000 picoseconds.
		Weight::from_parts(15_537_000, 6102)
			// Standard Error: 23_394
			.saturating_add(Weight::from_parts(10_699_515, 0).saturating_mul(b.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(b.into())))
	}
}