//! Autogenerated weights for pallet_avn_anchor
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 48.0.0
//! DATE: 2026-04-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-172-31-1-153`, CPU: `AMD EPYC 7R32`
//! EXECUTION: ``, WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./avn-parachain-collator
// benchmark
// pallet
// --chain
// dev
// --wasm-execution=compiled
// --template
// frame-weight-template.hbs
// --pallet
// pallet_avn_anchor
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// avn_anchor_weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_avn_anchor.
pub trait WeightInfo {
	fn register_chain_handler() -> Weight;
	fn update_chain_handler() -> Weight;
	fn submit_checkpoint_with_identity() -> Weight;
	fn signed_register_chain_handler() -> Weight;
	fn signed_update_chain_handler() -> Weight;
	fn signed_submit_checkpoint_with_identity() -> Weight;
	fn register_appchain() -> Weight;
	fn set_checkpoint_fee() -> Weight;
	fn set_appchain_period_reward() -> Weight;
	fn claim(n: u32) -> Weight;
	fn process_outstanding_rewards(n: u32) -> Weight;
	fn on_new_reward_period(n: u32) -> Weight;
	fn pay_node_period(n: u32) -> Weight;
	fn on_reward_paid() -> Weight;
}

/// Weights for pallet_avn_anchor using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn register_chain_handler() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_770_000 picoseconds.
		Weight::from_parts(5_070_000, 0)
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:2 w:2)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn update_chain_handler() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `139`
		//  Estimated: `6044`
		// Minimum execution time: 30_261_000 picoseconds.
		Weight::from_parts(30_821_000, 6044)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:1 w:0)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::OriginIdToCheckpoint` (r:1 w:1)
	/// Proof: `AvnAnchor::OriginIdToCheckpoint` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::NextCheckpointId` (r:1 w:1)
	/// Proof: `AvnAnchor::NextCheckpointId` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Nonces` (r:1 w:1)
	/// Proof: `AvnAnchor::Nonces` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::CheckpointFee` (r:1 w:0)
	/// Proof: `AvnAnchor::CheckpointFee` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Checkpoints` (r:0 w:1)
	/// Proof: `AvnAnchor::Checkpoints` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn submit_checkpoint_with_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `699`
		//  Estimated: `6196`
		// Minimum execution time: 128_653_000 picoseconds.
		Weight::from_parts(130_313_000, 6196)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	fn signed_register_chain_handler() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_191_000 picoseconds.
		Weight::from_parts(5_441_000, 0)
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:2 w:2)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Nonces` (r:1 w:1)
	/// Proof: `AvnAnchor::Nonces` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn signed_update_chain_handler() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `155`
		//  Estimated: `6044`
		// Minimum execution time: 140_914_000 picoseconds.
		Weight::from_parts(142_434_000, 6044)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:1 w:0)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Nonces` (r:1 w:1)
	/// Proof: `AvnAnchor::Nonces` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::OriginIdToCheckpoint` (r:1 w:1)
	/// Proof: `AvnAnchor::OriginIdToCheckpoint` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::NextCheckpointId` (r:1 w:1)
	/// Proof: `AvnAnchor::NextCheckpointId` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::CheckpointFee` (r:1 w:0)
	/// Proof: `AvnAnchor::CheckpointFee` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Checkpoints` (r:0 w:1)
	/// Proof: `AvnAnchor::Checkpoints` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn signed_submit_checkpoint_with_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `665`
		//  Estimated: `6196`
		// Minimum execution time: 238_735_000 picoseconds.
		Weight::from_parts(240_615_000, 6196)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:1 w:1)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:1)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::NextChainId` (r:1 w:1)
	/// Proof: `AvnAnchor::NextChainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::Metadata` (r:1 w:1)
	/// Proof: `AssetRegistry::Metadata` (`max_values`: None, `max_size`: Some(2698), added: 5173, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::RegisteredAppchains` (r:1 w:1)
	/// Proof: `AvnAnchor::RegisteredAppchains` (`max_values`: Some(1), `max_size`: Some(502), added: 997, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::AssetIdToChainId` (r:0 w:1)
	/// Proof: `AvnAnchor::AssetIdToChainId` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn register_appchain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `233`
		//  Estimated: `6163`
		// Minimum execution time: 49_821_000 picoseconds.
		Weight::from_parts(50_481_000, 6163)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `AvnAnchor::CheckpointFee` (r:0 w:1)
	/// Proof: `AvnAnchor::CheckpointFee` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn set_checkpoint_fee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 11_570_000 picoseconds.
		Weight::from_parts(11_920_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AvnAnchor::AssetIdToChainId` (r:1 w:0)
	/// Proof: `AvnAnchor::AssetIdToChainId` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::ChainHandlers` (r:1 w:0)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::NextRewardAmountPerPeriod` (r:0 w:1)
	/// Proof: `AvnAnchor::NextRewardAmountPerPeriod` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	fn set_appchain_period_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `177`
		//  Estimated: `3517`
		// Minimum execution time: 16_041_000 picoseconds.
		Weight::from_parts(18_797_000, 3517)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AvnAnchor::UnpaidByNode` (r:101 w:100)
	/// Proof: `AvnAnchor::UnpaidByNode` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::UnpaidByPeriod` (r:200 w:100)
	/// Proof: `AvnAnchor::UnpaidByPeriod` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::PeriodChainReward` (r:200 w:100)
	/// Proof: `AvnAnchor::PeriodChainReward` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `OrmlTokens::Accounts` (r:2 w:2)
	/// Proof: `OrmlTokens::Accounts` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::Metadata` (r:1 w:0)
	/// Proof: `AssetRegistry::Metadata` (`max_values`: None, `max_size`: Some(2698), added: 5173, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 100]`.
	fn claim(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `819 + n * (237 ±0)`
		//  Estimated: `6163 + n * (5174 ±0)`
		// Minimum execution time: 105_871_000 picoseconds.
		Weight::from_parts(644_357_887, 6163)
			// Standard Error: 658_125
			.saturating_add(Weight::from_parts(57_214_423, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().reads((5_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 5174).saturating_mul(n.into()))
	}
	/// Storage: `AvnAnchor::UnpaidByPeriod` (r:102 w:100)
	/// Proof: `AvnAnchor::UnpaidByPeriod` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::PeriodChainReward` (r:2 w:1)
	/// Proof: `AvnAnchor::PeriodChainReward` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `OrmlTokens::Accounts` (r:2 w:2)
	/// Proof: `OrmlTokens::Accounts` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::Metadata` (r:1 w:0)
	/// Proof: `AssetRegistry::Metadata` (`max_values`: None, `max_size`: Some(2698), added: 5173, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::UnpaidByNode` (r:100 w:100)
	/// Proof: `AvnAnchor::UnpaidByNode` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 100]`.
	fn process_outstanding_rewards(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `909 + n * (174 ±0)`
		//  Estimated: `6164 + n * (2587 ±0)`
		// Minimum execution time: 92_541_000 picoseconds.
		Weight::from_parts(103_659_000, 6164)
			// Standard Error: 362_252
			.saturating_add(Weight::from_parts(72_886_668, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(4_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2587).saturating_mul(n.into()))
	}
	/// Storage: `AvnAnchor::NextRewardAmountPerPeriod` (r:101 w:0)
	/// Proof: `AvnAnchor::NextRewardAmountPerPeriod` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::Metadata` (r:100 w:0)
	/// Proof: `AssetRegistry::Metadata` (`max_values`: None, `max_size`: Some(2698), added: 5173, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::PeriodChainReward` (r:0 w:100)
	/// Proof: `AvnAnchor::PeriodChainReward` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 100]`.
	fn on_new_reward_period(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `721 + n * (125 ±0)`
		//  Estimated: `3502 + n * (5173 ±0)`
		// Minimum execution time: 20_529_000 picoseconds.
		Weight::from_parts(64_417_398, 3502)
			// Standard Error: 120_289
			.saturating_add(Weight::from_parts(10_483_607, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 5173).saturating_mul(n.into()))
	}
	/// Storage: `AvnAnchor::UnpaidByPeriod` (r:2 w:1)
	/// Proof: `AvnAnchor::UnpaidByPeriod` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::PeriodChainReward` (r:101 w:100)
	/// Proof: `AvnAnchor::PeriodChainReward` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:100 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `OrmlTokens::Accounts` (r:200 w:200)
	/// Proof: `OrmlTokens::Accounts` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::Metadata` (r:100 w:0)
	/// Proof: `AssetRegistry::Metadata` (`max_values`: None, `max_size`: Some(2698), added: 5173, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::UnpaidByNode` (r:1 w:1)
	/// Proof: `AvnAnchor::UnpaidByNode` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 100]`.
	fn pay_node_period(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `866 + n * (258 ±0)`
		//  Estimated: `6164 + n * (5173 ±0)`
		// Minimum execution time: 88_850_000 picoseconds.
		Weight::from_parts(140_977_754, 6164)
			// Standard Error: 328_358
			.saturating_add(Weight::from_parts(44_267_857, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().reads((5_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 5173).saturating_mul(n.into()))
	}
	/// Storage: `AvnAnchor::PeriodChainReward` (r:2 w:0)
	/// Proof: `AvnAnchor::PeriodChainReward` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::UnpaidByPeriod` (r:0 w:1)
	/// Proof: `AvnAnchor::UnpaidByPeriod` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::UnpaidByNode` (r:0 w:1)
	/// Proof: `AvnAnchor::UnpaidByNode` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	fn on_reward_paid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `261`
		//  Estimated: `6102`
		// Minimum execution time: 15_625_000 picoseconds.
		Weight::from_parts(17_474_000, 6102)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	fn register_chain_handler() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_770_000 picoseconds.
		Weight::from_parts(5_070_000, 0)
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:2 w:2)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn update_chain_handler() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `139`
		//  Estimated: `6044`
		// Minimum execution time: 30_261_000 picoseconds.
		Weight::from_parts(30_821_000, 6044)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:1 w:0)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::OriginIdToCheckpoint` (r:1 w:1)
	/// Proof: `AvnAnchor::OriginIdToCheckpoint` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::NextCheckpointId` (r:1 w:1)
	/// Proof: `AvnAnchor::NextCheckpointId` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Nonces` (r:1 w:1)
	/// Proof: `AvnAnchor::Nonces` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::CheckpointFee` (r:1 w:0)
	/// Proof: `AvnAnchor::CheckpointFee` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Checkpoints` (r:0 w:1)
	/// Proof: `AvnAnchor::Checkpoints` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn submit_checkpoint_with_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `699`
		//  Estimated: `6196`
		// Minimum execution time: 128_653_000 picoseconds.
		Weight::from_parts(130_313_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	fn signed_register_chain_handler() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_191_000 picoseconds.
		Weight::from_parts(5_441_000, 0)
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:2 w:2)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Nonces` (r:1 w:1)
	/// Proof: `AvnAnchor::Nonces` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn signed_update_chain_handler() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `155`
		//  Estimated: `6044`
		// Minimum execution time: 140_914_000 picoseconds.
		Weight::from_parts(142_434_000, 6044)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:1 w:0)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Nonces` (r:1 w:1)
	/// Proof: `AvnAnchor::Nonces` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::OriginIdToCheckpoint` (r:1 w:1)
	/// Proof: `AvnAnchor::OriginIdToCheckpoint` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::NextCheckpointId` (r:1 w:1)
	/// Proof: `AvnAnchor::NextCheckpointId` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::CheckpointFee` (r:1 w:0)
	/// Proof: `AvnAnchor::CheckpointFee` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `TokenManager::AVTTokenContract` (r:1 w:0)
	/// Proof: `TokenManager::AVTTokenContract` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::Checkpoints` (r:0 w:1)
	/// Proof: `AvnAnchor::Checkpoints` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn signed_submit_checkpoint_with_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `665`
		//  Estimated: `6196`
		// Minimum execution time: 238_735_000 picoseconds.
		Weight::from_parts(240_615_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `AvnAnchor::ChainHandlers` (r:1 w:1)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:1)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::NextChainId` (r:1 w:1)
	/// Proof: `AvnAnchor::NextChainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::Metadata` (r:1 w:1)
	/// Proof: `AssetRegistry::Metadata` (`max_values`: None, `max_size`: Some(2698), added: 5173, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::RegisteredAppchains` (r:1 w:1)
	/// Proof: `AvnAnchor::RegisteredAppchains` (`max_values`: Some(1), `max_size`: Some(502), added: 997, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::AssetIdToChainId` (r:0 w:1)
	/// Proof: `AvnAnchor::AssetIdToChainId` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn register_appchain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `233`
		//  Estimated: `6163`
		// Minimum execution time: 49_821_000 picoseconds.
		Weight::from_parts(50_481_000, 6163)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `AvnAnchor::CheckpointFee` (r:0 w:1)
	/// Proof: `AvnAnchor::CheckpointFee` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn set_checkpoint_fee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 11_570_000 picoseconds.
		Weight::from_parts(11_920_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AvnAnchor::AssetIdToChainId` (r:1 w:0)
	/// Proof: `AvnAnchor::AssetIdToChainId` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::ChainHandlers` (r:1 w:0)
	/// Proof: `AvnAnchor::ChainHandlers` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::NextRewardAmountPerPeriod` (r:0 w:1)
	/// Proof: `AvnAnchor::NextRewardAmountPerPeriod` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	fn set_appchain_period_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `177`
		//  Estimated: `3517`
		// Minimum execution time: 16_041_000 picoseconds.
		Weight::from_parts(18_797_000, 3517)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AvnAnchor::UnpaidByNode` (r:101 w:100)
	/// Proof: `AvnAnchor::UnpaidByNode` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::UnpaidByPeriod` (r:200 w:100)
	/// Proof: `AvnAnchor::UnpaidByPeriod` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::PeriodChainReward` (r:200 w:100)
	/// Proof: `AvnAnchor::PeriodChainReward` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `OrmlTokens::Accounts` (r:2 w:2)
	/// Proof: `OrmlTokens::Accounts` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::Metadata` (r:1 w:0)
	/// Proof: `AssetRegistry::Metadata` (`max_values`: None, `max_size`: Some(2698), added: 5173, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 100]`.
	fn claim(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `819 + n * (237 ±0)`
		//  Estimated: `6163 + n * (5174 ±0)`
		// Minimum execution time: 105_871_000 picoseconds.
		Weight::from_parts(644_357_887, 6163)
			// Standard Error: 658_125
			.saturating_add(Weight::from_parts(57_214_423, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().reads((5_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
			.saturating_add(RocksDbWeight::get().writes((3_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 5174).saturating_mul(n.into()))
	}
	/// Storage: `AvnAnchor::UnpaidByPeriod` (r:102 w:100)
	/// Proof: `AvnAnchor::UnpaidByPeriod` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::PeriodChainReward` (r:2 w:1)
	/// Proof: `AvnAnchor::PeriodChainReward` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:1 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `OrmlTokens::Accounts` (r:2 w:2)
	/// Proof: `OrmlTokens::Accounts` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::Metadata` (r:1 w:0)
	/// Proof: `AssetRegistry::Metadata` (`max_values`: None, `max_size`: Some(2698), added: 5173, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::UnpaidByNode` (r:100 w:100)
	/// Proof: `AvnAnchor::UnpaidByNode` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 100]`.
	fn process_outstanding_rewards(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `909 + n * (174 ±0)`
		//  Estimated: `6164 + n * (2587 ±0)`
		// Minimum execution time: 92_541_000 picoseconds.
		Weight::from_parts(103_659_000, 6164)
			// Standard Error: 362_252
			.saturating_add(Weight::from_parts(72_886_668, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2587).saturating_mul(n.into()))
	}
	/// Storage: `AvnAnchor::NextRewardAmountPerPeriod` (r:101 w:0)
	/// Proof: `AvnAnchor::NextRewardAmountPerPeriod` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::Metadata` (r:100 w:0)
	/// Proof: `AssetRegistry::Metadata` (`max_values`: None, `max_size`: Some(2698), added: 5173, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::PeriodChainReward` (r:0 w:100)
	/// Proof: `AvnAnchor::PeriodChainReward` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 100]`.
	fn on_new_reward_period(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `721 + n * (125 ±0)`
		//  Estimated: `3502 + n * (5173 ±0)`
		// Minimum execution time: 20_529_000 picoseconds.
		Weight::from_parts(64_417_398, 3502)
			// Standard Error: 120_289
			.saturating_add(Weight::from_parts(10_483_607, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 5173).saturating_mul(n.into()))
	}
	/// Storage: `AvnAnchor::UnpaidByPeriod` (r:2 w:1)
	/// Proof: `AvnAnchor::UnpaidByPeriod` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::PeriodChainReward` (r:101 w:100)
	/// Proof: `AvnAnchor::PeriodChainReward` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::LocationToAssetId` (r:100 w:0)
	/// Proof: `AssetRegistry::LocationToAssetId` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `OrmlTokens::Accounts` (r:200 w:200)
	/// Proof: `OrmlTokens::Accounts` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `AssetRegistry::Metadata` (r:100 w:0)
	/// Proof: `AssetRegistry::Metadata` (`max_values`: None, `max_size`: Some(2698), added: 5173, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::UnpaidByNode` (r:1 w:1)
	/// Proof: `AvnAnchor::UnpaidByNode` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 100]`.
	fn pay_node_period(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `866 + n * (258 ±0)`
		//  Estimated: `6164 + n * (5173 ±0)`
		// Minimum execution time: 88_850_000 picoseconds.
		Weight::from_parts(140_977_754, 6164)
			// Standard Error: 328_358
			.saturating_add(Weight::from_parts(44_267_857, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().reads((5_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
			.saturating_add(RocksDbWeight::get().writes((3_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 5173).saturating_mul(n.into()))
	}
	/// Storage: `AvnAnchor::PeriodChainReward` (r:2 w:0)
	/// Proof: `AvnAnchor::PeriodChainReward` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::UnpaidByPeriod` (r:0 w:1)
	/// Proof: `AvnAnchor::UnpaidByPeriod` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `AvnAnchor::UnpaidByNode` (r:0 w:1)
	/// Proof: `AvnAnchor::UnpaidByNode` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	fn on_reward_paid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `261`
		//  Estimated: `6102`
		// Minimum execution time: 15_625_000 picoseconds.
		Weight::from_parts(17_474_000, 6102)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}