//! Autogenerated weights for pallet_watchtower
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 48.0.0
//! DATE: 2026-04-02, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-172-31-1-153`, CPU: `AMD EPYC 7R32`
//! EXECUTION: ``, WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./avn-parachain-collator
// benchmark
// pallet
// --chain
// dev
// --wasm-execution=compiled
// --template
// frame-weight-template.hbs
// --pallet
// pallet_watchtower
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// watchtower_weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_watchtower.
pub trait WeightInfo {
	fn submit_external_proposal() -> Weight;
	fn signed_submit_external_proposal() -> Weight;
	fn vote() -> Weight;
	fn vote_end_proposal() -> Weight;
	fn signed_vote() -> Weight;
	fn signed_vote_end_proposal() -> Weight;
	fn unsigned_vote() -> Weight;
	fn unsigned_vote_end_proposal() -> Weight;
	fn finalise_proposal() -> Weight;
	fn set_admin_config_voting() -> Weight;
	fn set_admin_config_account() -> Weight;
	fn active_proposal_expiry_status() -> Weight;
	fn finalise_expired_voting() -> Weight;
	fn activate_next_proposal(k: u32, ) -> Weight;
	fn activate_next_proposal_hook_fails(k: u32, ) -> Weight;
	fn demote_queue_head() -> Weight;
	fn cancel_queue_head() -> Weight;
}

/// Weights for pallet_watchtower using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Watchtower::AdminAccount` (r:1 w:0)
	/// Proof: `Watchtower::AdminAccount` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::MinVotingPeriod` (r:1 w:0)
	/// Proof: `Watchtower::MinVotingPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ExternalRef` (r:1 w:1)
	/// Proof: `Watchtower::ExternalRef` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:1)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(8848), added: 11323, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:0 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	fn submit_external_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `12308`
		// Minimum execution time: 33_841_000 picoseconds.
		Weight::from_parts(34_571_000, 12308)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Watchtower::AdminAccount` (r:1 w:0)
	/// Proof: `Watchtower::AdminAccount` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::MinVotingPeriod` (r:1 w:0)
	/// Proof: `Watchtower::MinVotingPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ExternalRef` (r:1 w:1)
	/// Proof: `Watchtower::ExternalRef` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:1)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(8848), added: 11323, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:0 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	fn signed_submit_external_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `12308`
		// Minimum execution time: 143_343_000 picoseconds.
		Weight::from_parts(145_823_000, 12308)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(8848), added: 11323, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:0)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Voters` (r:1 w:1)
	/// Proof: `Watchtower::Voters` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommitteeSize` (r:1 w:0)
	/// Proof: `Watchtower::ProposalCommitteeSize` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommittee` (r:1 w:0)
	/// Proof: `Watchtower::ProposalCommittee` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:0)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Votes` (r:1 w:1)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `521`
		//  Estimated: `12313`
		// Minimum execution time: 42_644_000 picoseconds.
		Weight::from_parts(58_129_000, 12313)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(8848), added: 11323, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Voters` (r:1 w:1)
	/// Proof: `Watchtower::Voters` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommitteeSize` (r:1 w:0)
	/// Proof: `Watchtower::ProposalCommitteeSize` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommittee` (r:1 w:0)
	/// Proof: `Watchtower::ProposalCommittee` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:1)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Votes` (r:1 w:1)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `SummaryWatchtower::RootInfo` (r:1 w:0)
	/// Proof: `SummaryWatchtower::RootInfo` (`max_values`: Some(1), `max_size`: Some(80), added: 575, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalsToRemove` (r:0 w:1)
	/// Proof: `Watchtower::ProposalsToRemove` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn vote_end_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1126`
		//  Estimated: `12313`
		// Minimum execution time: 62_424_000 picoseconds.
		Weight::from_parts(80_336_000, 12313)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(8848), added: 11323, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:0)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Voters` (r:1 w:1)
	/// Proof: `Watchtower::Voters` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommitteeSize` (r:1 w:0)
	/// Proof: `Watchtower::ProposalCommitteeSize` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommittee` (r:1 w:0)
	/// Proof: `Watchtower::ProposalCommittee` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:0)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Votes` (r:1 w:1)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn signed_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `521`
		//  Estimated: `12313`
		// Minimum execution time: 116_452_000 picoseconds.
		Weight::from_parts(139_074_000, 12313)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(8848), added: 11323, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Voters` (r:1 w:1)
	/// Proof: `Watchtower::Voters` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommitteeSize` (r:1 w:0)
	/// Proof: `Watchtower::ProposalCommitteeSize` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommittee` (r:1 w:0)
	/// Proof: `Watchtower::ProposalCommittee` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:1)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Votes` (r:1 w:1)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `SummaryWatchtower::RootInfo` (r:1 w:0)
	/// Proof: `SummaryWatchtower::RootInfo` (`max_values`: Some(1), `max_size`: Some(80), added: 575, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalsToRemove` (r:0 w:1)
	/// Proof: `Watchtower::ProposalsToRemove` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn signed_vote_end_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1126`
		//  Estimated: `12313`
		// Minimum execution time: 139_528_000 picoseconds.
		Weight::from_parts(201_278_000, 12313)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:0)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommitteeSize` (r:1 w:0)
	/// Proof: `Watchtower::ProposalCommitteeSize` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommittee` (r:1 w:0)
	/// Proof: `Watchtower::ProposalCommittee` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(8848), added: 11323, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:0)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Voters` (r:1 w:1)
	/// Proof: `Watchtower::Voters` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Votes` (r:1 w:1)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn unsigned_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `521`
		//  Estimated: `12313`
		// Minimum execution time: 88_238_000 picoseconds.
		Weight::from_parts(123_095_000, 12313)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:1)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommitteeSize` (r:1 w:0)
	/// Proof: `Watchtower::ProposalCommitteeSize` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommittee` (r:1 w:0)
	/// Proof: `Watchtower::ProposalCommittee` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(8848), added: 11323, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Voters` (r:1 w:1)
	/// Proof: `Watchtower::Voters` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Votes` (r:1 w:1)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `SummaryWatchtower::RootInfo` (r:1 w:0)
	/// Proof: `SummaryWatchtower::RootInfo` (`max_values`: Some(1), `max_size`: Some(80), added: 575, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalsToRemove` (r:0 w:1)
	/// Proof: `Watchtower::ProposalsToRemove` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn unsigned_vote_end_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1126`
		//  Estimated: `12313`
		// Minimum execution time: 111_391_000 picoseconds.
		Weight::from_parts(157_306_000, 12313)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(8848), added: 11323, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Votes` (r:1 w:0)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `SummaryWatchtower::RootInfo` (r:1 w:0)
	/// Proof: `SummaryWatchtower::RootInfo` (`max_values`: Some(1), `max_size`: Some(80), added: 575, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:1)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalsToRemove` (r:0 w:1)
	/// Proof: `Watchtower::ProposalsToRemove` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn finalise_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `755`
		//  Estimated: `12313`
		// Minimum execution time: 41_082_000 picoseconds.
		Weight::from_parts(52_371_000, 12313)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Watchtower::MinVotingPeriod` (r:1 w:1)
	/// Proof: `Watchtower::MinVotingPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_admin_config_voting() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `1489`
		// Minimum execution time: 12_940_000 picoseconds.
		Weight::from_parts(13_220_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Watchtower::AdminAccount` (r:1 w:1)
	/// Proof: `Watchtower::AdminAccount` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn set_admin_config_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `1517`
		// Minimum execution time: 13_180_000 picoseconds.
		Weight::from_parts(13_600_000, 1517)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:0)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(8848), added: 11323, mode: `MaxEncodedLen`)
	fn active_proposal_expiry_status() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `334`
		//  Estimated: `12313`
		// Minimum execution time: 7_652_000 picoseconds.
		Weight::from_parts(9_620_000, 12313)
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
	/// Storage: `Watchtower::Votes` (r:1 w:0)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `SummaryWatchtower::RootInfo` (r:1 w:0)
	/// Proof: `SummaryWatchtower::RootInfo` (`max_values`: Some(1), `max_size`: Some(80), added: 575, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:1)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:0 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalsToRemove` (r:0 w:1)
	/// Proof: `Watchtower::ProposalsToRemove` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn finalise_expired_voting() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `461`
		//  Estimated: `3529`
		// Minimum execution time: 24_403_000 picoseconds.
		Weight::from_parts(31_981_000, 3529)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Watchtower::Tail` (r:1 w:0)
	/// Proof: `Watchtower::Tail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Head` (r:1 w:1)
	/// Proof: `Watchtower::Head` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::InternalProposalQueue` (r:1 w:1)
	/// Proof: `Watchtower::InternalProposalQueue` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:1)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:1)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(8848), added: 11323, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommittee` (r:500 w:500)
	/// Proof: `Watchtower::ProposalCommittee` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `SummaryWatchtower::RootInfo` (r:1 w:1)
	/// Proof: `SummaryWatchtower::RootInfo` (`max_values`: Some(1), `max_size`: Some(80), added: 575, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:0 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommitteeSize` (r:0 w:1)
	/// Proof: `Watchtower::ProposalCommitteeSize` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::ValidationData` (r:1 w:0)
	/// Proof: `ParachainSystem::ValidationData` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::ParentHash` (r:1 w:0)
	/// Proof: `System::ParentHash` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// The range of component `k` is `[10, 500]`.
	fn activate_next_proposal(k: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `391`
		//  Estimated: `12313 + k * (2571 ±0)`
		// Minimum execution time: 120_183_000 picoseconds.
		Weight::from_parts(75_044_817, 12313)
			// Standard Error: 29_994
			.saturating_add(Weight::from_parts(7_454_659, 0).saturating_mul(k.into()))
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(k.into())))
			.saturating_add(T::DbWeight::get().writes(7_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(k.into())))
			.saturating_add(Weight::from_parts(0, 2571).saturating_mul(k.into()))
	}
	/// Storage: `Watchtower::Tail` (r:1 w:0)
	/// Proof: `Watchtower::Tail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Head` (r:1 w:1)
	/// Proof: `Watchtower::Head` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::InternalProposalQueue` (r:1 w:1)
	/// Proof: `Watchtower::InternalProposalQueue` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:1)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:1)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(8848), added: 11323, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommittee` (r:500 w:500)
	/// Proof: `Watchtower::ProposalCommittee` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `SummaryWatchtower::RootInfo` (r:1 w:0)
	/// Proof: `SummaryWatchtower::RootInfo` (`max_values`: Some(1), `max_size`: Some(80), added: 575, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:0 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalsToRemove` (r:0 w:1)
	/// Proof: `Watchtower::ProposalsToRemove` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommitteeSize` (r:0 w:1)
	/// Proof: `Watchtower::ProposalCommitteeSize` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::ValidationData` (r:1 w:0)
	/// Proof: `ParachainSystem::ValidationData` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::ParentHash` (r:1 w:0)
	/// Proof: `System::ParentHash` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// The range of component `k` is `[10, 500]`.
	fn activate_next_proposal_hook_fails(k: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `502`
		//  Estimated: `12313 + k * (2571 ±0)`
		// Minimum execution time: 148_555_000 picoseconds.
		Weight::from_parts(91_082_031, 12313)
			// Standard Error: 30_711
			.saturating_add(Weight::from_parts(8_291_765, 0).saturating_mul(k.into()))
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(k.into())))
			.saturating_add(T::DbWeight::get().writes(7_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(k.into())))
			.saturating_add(Weight::from_parts(0, 2571).saturating_mul(k.into()))
	}
	/// Storage: `Watchtower::Tail` (r:1 w:0)
	/// Proof: `Watchtower::Tail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Head` (r:1 w:0)
	/// Proof: `Watchtower::Head` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::InternalProposalQueue` (r:2 w:2)
	/// Proof: `Watchtower::InternalProposalQueue` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	fn demote_queue_head() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `216`
		//  Estimated: `6046`
		// Minimum execution time: 25_084_000 picoseconds.
		Weight::from_parts(33_135_000, 6046)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Watchtower::Tail` (r:1 w:0)
	/// Proof: `Watchtower::Tail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Head` (r:1 w:1)
	/// Proof: `Watchtower::Head` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::InternalProposalQueue` (r:1 w:1)
	/// Proof: `Watchtower::InternalProposalQueue` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(8848), added: 11323, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `SummaryWatchtower::RootInfo` (r:1 w:0)
	/// Proof: `SummaryWatchtower::RootInfo` (`max_values`: Some(1), `max_size`: Some(80), added: 575, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:0)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:0 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalsToRemove` (r:0 w:1)
	/// Proof: `Watchtower::ProposalsToRemove` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn cancel_queue_head() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `609`
		//  Estimated: `12313`
		// Minimum execution time: 41_822_000 picoseconds.
		Weight::from_parts(59_511_000, 12313)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Watchtower::AdminAccount` (r:1 w:0)
	/// Proof: `Watchtower::AdminAccount` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::MinVotingPeriod` (r:1 w:0)
	/// Proof: `Watchtower::MinVotingPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ExternalRef` (r:1 w:1)
	/// Proof: `Watchtower::ExternalRef` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:1)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(8848), added: 11323, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:0 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	fn submit_external_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `12308`
		// Minimum execution time: 33_841_000 picoseconds.
		Weight::from_parts(34_571_000, 12308)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Watchtower::AdminAccount` (r:1 w:0)
	/// Proof: `Watchtower::AdminAccount` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::MinVotingPeriod` (r:1 w:0)
	/// Proof: `Watchtower::MinVotingPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ExternalRef` (r:1 w:1)
	/// Proof: `Watchtower::ExternalRef` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:1)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(8848), added: 11323, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:0 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	fn signed_submit_external_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `12308`
		// Minimum execution time: 143_343_000 picoseconds.
		Weight::from_parts(145_823_000, 12308)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(8848), added: 11323, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:0)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Voters` (r:1 w:1)
	/// Proof: `Watchtower::Voters` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommitteeSize` (r:1 w:0)
	/// Proof: `Watchtower::ProposalCommitteeSize` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommittee` (r:1 w:0)
	/// Proof: `Watchtower::ProposalCommittee` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:0)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Votes` (r:1 w:1)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `521`
		//  Estimated: `12313`
		// Minimum execution time: 42_644_000 picoseconds.
		Weight::from_parts(58_129_000, 12313)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(8848), added: 11323, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Voters` (r:1 w:1)
	/// Proof: `Watchtower::Voters` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommitteeSize` (r:1 w:0)
	/// Proof: `Watchtower::ProposalCommitteeSize` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommittee` (r:1 w:0)
	/// Proof: `Watchtower::ProposalCommittee` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:1)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Votes` (r:1 w:1)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `SummaryWatchtower::RootInfo` (r:1 w:0)
	/// Proof: `SummaryWatchtower::RootInfo` (`max_values`: Some(1), `max_size`: Some(80), added: 575, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalsToRemove` (r:0 w:1)
	/// Proof: `Watchtower::ProposalsToRemove` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn vote_end_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1126`
		//  Estimated: `12313`
		// Minimum execution time: 62_424_000 picoseconds.
		Weight::from_parts(80_336_000, 12313)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(8848), added: 11323, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:0)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Voters` (r:1 w:1)
	/// Proof: `Watchtower::Voters` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommitteeSize` (r:1 w:0)
	/// Proof: `Watchtower::ProposalCommitteeSize` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommittee` (r:1 w:0)
	/// Proof: `Watchtower::ProposalCommittee` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:0)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Votes` (r:1 w:1)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn signed_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `521`
		//  Estimated: `12313`
		// Minimum execution time: 116_452_000 picoseconds.
		Weight::from_parts(139_074_000, 12313)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(8848), added: 11323, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Voters` (r:1 w:1)
	/// Proof: `Watchtower::Voters` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommitteeSize` (r:1 w:0)
	/// Proof: `Watchtower::ProposalCommitteeSize` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommittee` (r:1 w:0)
	/// Proof: `Watchtower::ProposalCommittee` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:1)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Votes` (r:1 w:1)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `SummaryWatchtower::RootInfo` (r:1 w:0)
	/// Proof: `SummaryWatchtower::RootInfo` (`max_values`: Some(1), `max_size`: Some(80), added: 575, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalsToRemove` (r:0 w:1)
	/// Proof: `Watchtower::ProposalsToRemove` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn signed_vote_end_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1126`
		//  Estimated: `12313`
		// Minimum execution time: 139_528_000 picoseconds.
		Weight::from_parts(201_278_000, 12313)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:0)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommitteeSize` (r:1 w:0)
	/// Proof: `Watchtower::ProposalCommitteeSize` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommittee` (r:1 w:0)
	/// Proof: `Watchtower::ProposalCommittee` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(8848), added: 11323, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:0)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Voters` (r:1 w:1)
	/// Proof: `Watchtower::Voters` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Votes` (r:1 w:1)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn unsigned_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `521`
		//  Estimated: `12313`
		// Minimum execution time: 88_238_000 picoseconds.
		Weight::from_parts(123_095_000, 12313)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:1)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommitteeSize` (r:1 w:0)
	/// Proof: `Watchtower::ProposalCommitteeSize` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommittee` (r:1 w:0)
	/// Proof: `Watchtower::ProposalCommittee` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(8848), added: 11323, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Voters` (r:1 w:1)
	/// Proof: `Watchtower::Voters` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Votes` (r:1 w:1)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `SummaryWatchtower::RootInfo` (r:1 w:0)
	/// Proof: `SummaryWatchtower::RootInfo` (`max_values`: Some(1), `max_size`: Some(80), added: 575, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalsToRemove` (r:0 w:1)
	/// Proof: `Watchtower::ProposalsToRemove` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn unsigned_vote_end_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1126`
		//  Estimated: `12313`
		// Minimum execution time: 111_391_000 picoseconds.
		Weight::from_parts(157_306_000, 12313)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(8848), added: 11323, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:1 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Votes` (r:1 w:0)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `SummaryWatchtower::RootInfo` (r:1 w:0)
	/// Proof: `SummaryWatchtower::RootInfo` (`max_values`: Some(1), `max_size`: Some(80), added: 575, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:1)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalsToRemove` (r:0 w:1)
	/// Proof: `Watchtower::ProposalsToRemove` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn finalise_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `755`
		//  Estimated: `12313`
		// Minimum execution time: 41_082_000 picoseconds.
		Weight::from_parts(52_371_000, 12313)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Watchtower::MinVotingPeriod` (r:1 w:1)
	/// Proof: `Watchtower::MinVotingPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_admin_config_voting() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `1489`
		// Minimum execution time: 12_940_000 picoseconds.
		Weight::from_parts(13_220_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Watchtower::AdminAccount` (r:1 w:1)
	/// Proof: `Watchtower::AdminAccount` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn set_admin_config_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `1517`
		// Minimum execution time: 13_180_000 picoseconds.
		Weight::from_parts(13_600_000, 1517)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:0)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(8848), added: 11323, mode: `MaxEncodedLen`)
	fn active_proposal_expiry_status() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `334`
		//  Estimated: `12313`
		// Minimum execution time: 7_652_000 picoseconds.
		Weight::from_parts(9_620_000, 12313)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
	}
	/// Storage: `Watchtower::Votes` (r:1 w:0)
	/// Proof: `Watchtower::Votes` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `SummaryWatchtower::RootInfo` (r:1 w:0)
	/// Proof: `SummaryWatchtower::RootInfo` (`max_values`: Some(1), `max_size`: Some(80), added: 575, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:1)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:0 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalsToRemove` (r:0 w:1)
	/// Proof: `Watchtower::ProposalsToRemove` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn finalise_expired_voting() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `461`
		//  Estimated: `3529`
		// Minimum execution time: 24_403_000 picoseconds.
		Weight::from_parts(31_981_000, 3529)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Watchtower::Tail` (r:1 w:0)
	/// Proof: `Watchtower::Tail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Head` (r:1 w:1)
	/// Proof: `Watchtower::Head` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::InternalProposalQueue` (r:1 w:1)
	/// Proof: `Watchtower::InternalProposalQueue` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:1)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:1)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(8848), added: 11323, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommittee` (r:500 w:500)
	/// Proof: `Watchtower::ProposalCommittee` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `SummaryWatchtower::RootInfo` (r:1 w:1)
	/// Proof: `SummaryWatchtower::RootInfo` (`max_values`: Some(1), `max_size`: Some(80), added: 575, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:0 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommitteeSize` (r:0 w:1)
	/// Proof: `Watchtower::ProposalCommitteeSize` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::ValidationData` (r:1 w:0)
	/// Proof: `ParachainSystem::ValidationData` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::ParentHash` (r:1 w:0)
	/// Proof: `System::ParentHash` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// The range of component `k` is `[10, 500]`.
	fn activate_next_proposal(k: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `391`
		//  Estimated: `12313 + k * (2571 ±0)`
		// Minimum execution time: 120_183_000 picoseconds.
		Weight::from_parts(75_044_817, 12313)
			// Standard Error: 29_994
			.saturating_add(Weight::from_parts(7_454_659, 0).saturating_mul(k.into()))
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(k.into())))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(k.into())))
			.saturating_add(Weight::from_parts(0, 2571).saturating_mul(k.into()))
	}
	/// Storage: `Watchtower::Tail` (r:1 w:0)
	/// Proof: `Watchtower::Tail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Head` (r:1 w:1)
	/// Proof: `Watchtower::Head` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::InternalProposalQueue` (r:1 w:1)
	/// Proof: `Watchtower::InternalProposalQueue` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:1)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:1)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(8848), added: 11323, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommittee` (r:500 w:500)
	/// Proof: `Watchtower::ProposalCommittee` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `SummaryWatchtower::RootInfo` (r:1 w:0)
	/// Proof: `SummaryWatchtower::RootInfo` (`max_values`: Some(1), `max_size`: Some(80), added: 575, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:0 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalsToRemove` (r:0 w:1)
	/// Proof: `Watchtower::ProposalsToRemove` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalCommitteeSize` (r:0 w:1)
	/// Proof: `Watchtower::ProposalCommitteeSize` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::ValidationData` (r:1 w:0)
	/// Proof: `ParachainSystem::ValidationData` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::ParentHash` (r:1 w:0)
	/// Proof: `System::ParentHash` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// The range of component `k` is `[10, 500]`.
	fn activate_next_proposal_hook_fails(k: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `502`
		//  Estimated: `12313 + k * (2571 ±0)`
		// Minimum execution time: 148_555_000 picoseconds.
		Weight::from_parts(91_082_031, 12313)
			// Standard Error: 30_711
			.saturating_add(Weight::from_parts(8_291_765, 0).saturating_mul(k.into()))
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(k.into())))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(k.into())))
			.saturating_add(Weight::from_parts(0, 2571).saturating_mul(k.into()))
	}
	/// Storage: `Watchtower::Tail` (r:1 w:0)
	/// Proof: `Watchtower::Tail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Head` (r:1 w:0)
	/// Proof: `Watchtower::Head` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::InternalProposalQueue` (r:2 w:2)
	/// Proof: `Watchtower::InternalProposalQueue` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	fn demote_queue_head() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `216`
		//  Estimated: `6046`
		// Minimum execution time: 25_084_000 picoseconds.
		Weight::from_parts(33_135_000, 6046)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Watchtower::Tail` (r:1 w:0)
	/// Proof: `Watchtower::Tail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Head` (r:1 w:1)
	/// Proof: `Watchtower::Head` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::InternalProposalQueue` (r:1 w:1)
	/// Proof: `Watchtower::InternalProposalQueue` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::Proposals` (r:1 w:0)
	/// Proof: `Watchtower::Proposals` (`max_values`: None, `max_size`: Some(8848), added: 11323, mode: `MaxEncodedLen`)
	/// Storage: `Summary::ExternalValidationRef` (r:1 w:0)
	/// Proof: `Summary::ExternalValidationRef` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `SummaryWatchtower::RootInfo` (r:1 w:0)
	/// Proof: `SummaryWatchtower::RootInfo` (`max_values`: Some(1), `max_size`: Some(80), added: 575, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ActiveInternalProposal` (r:1 w:0)
	/// Proof: `Watchtower::ActiveInternalProposal` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalStatus` (r:0 w:1)
	/// Proof: `Watchtower::ProposalStatus` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Watchtower::ProposalsToRemove` (r:0 w:1)
	/// Proof: `Watchtower::ProposalsToRemove` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn cancel_queue_head() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `609`
		//  Estimated: `12313`
		// Minimum execution time: 41_822_000 picoseconds.
		Weight::from_parts(59_511_000, 12313)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
}